# General Window Settings
[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "None"     
#opacity = 0.9                # Slight transparency (requires a compositor like picom)

[scrolling]
history = 10000
multiplier = 3

# Font Configuration
[font]
size = 7.0


[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

[colors.normal]
black   = "#15161e"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#a9b1d6"

[colors.bright]
black   = "#414868"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#c0caf5"

[cursor]
style = { shape = "Beam", blinking = "On" }
